-- アナウンステーブル
  CREATE TABLE announcement (
      ANNOUNCEMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
      TITLE VARCHAR(100) NOT NULL,
      CONTENT TEXT NOT NULL,
      IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
      DISPLAY_ORDER INT DEFAULT 0,
      IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
      DELETED_AT DATETIME,
      DELETED_BY VARCHAR(10),
      CREATED_AT DATETIME NOT NULL,
      CREATED_BY VARCHAR(10) NOT NULL,
      UPDATED_AT DATETIME NOT NULL,
      UPDATED_BY VARCHAR(10) NOT NULL
  );