DB-TBL作成SQL
1.kintai DB作成
CREATE DATABASE kintai  CHARACTER SET utf8;

2.kintaiDB使用
Use kintai;

--
--マスタ参照系（部署・社員・プロジェクトなど） → ON DELETE RESTRICT ON UPDATE CASCADE
--履歴・明細系（休憩・工数など）→ ON DELETE CASCADE ON UPDATE CASCADE
--中間的なもの（leave_rec, leave_balance）→ RESTRICT

-- IS_DELETED: 論理削除フラグ（TRUE=削除済、FALSE=現役）
-- CREATED_BY/UPDATED_BY: 操作を行った社員のEMP_ID
-- STATUS: 申請状態（例：申請中、承認済、却下）/現在使用しない

-- 権限テーブル
CREATE TABLE role (
  ROLE_ID INT PRIMARY KEY,
  ROLE_NAME VARCHAR(50) NOT NULL
);

-- 部署テーブル
CREATE TABLE dept (
  DEPT_ID VARCHAR(5) PRIMARY KEY,
  DEPT_NAME VARCHAR(50) NOT NULL,
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  DELETED_AT DATETIME DEFAULT NULL,
  DELETED_BY VARCHAR(10),
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY VARCHAR(10) NOT NULL,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(10) NOT NULL
);

-- 役職テーブル
CREATE TABLE post (
    POST_ID VARCHAR(5) PRIMARY KEY,
    POST_NAME VARCHAR(50) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL
);

-- 社員情報
CREATE TABLE emp (
    EMP_ID VARCHAR(10) PRIMARY KEY,
    EMP_NAME VARCHAR(50) NOT NULL,
    DEPT_ID VARCHAR(5) NOT NULL,
    POST_ID VARCHAR(5) NOT NULL,
    ROLE_ID INT NOT NULL,
    EMP_TYPE VARCHAR(10) NOT NULL,
    PASS VARCHAR(64) NOT NULL,
    MAIL VARCHAR(100),
    EMP_DATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    LEAVE_DATE DATE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL
    FOREIGN KEY (DEPT_ID) REFERENCES dept(DEPT_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES post(POST_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES role(ROLE_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 休暇種別
CREATE TABLE leave_type (
    LEAVE_TYPE_ID INT PRIMARY KEY,
    LEAVE_TYPE_NAME VARCHAR(50) NOT NULL,
    IS_PAID BOOLEAN NOT NULL,
    IS_SYSTEM_DEFINED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL,show
);

-- プロジェクト
CREATE TABLE project (
    PROJECT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_NAME VARCHAR(100) NOT NULL,
    BUDGET_AMOUNT INT,
    ACTUAL_COST INT,
    ACTUAL_LABOR_COST INT,
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL
);


-- カレンダーイベント
CREATE TABLE calendar_event (
    EVENT_DATE DATE PRIMARY KEY,
    EVENT_NAME VARCHAR(100) NOT NULL,
    IS_WORK BOOLEAN NOT NULL,
    IS_SYSTEM_DEFINED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL
);

-- 勤怠
CREATE TABLE kintai (
    KINTAI_REC_ID INT PRIMARY KEY AUTO_INCREMENT,
    KINTAI_DATE DATE NOT NULL,
    EMP_ID VARCHAR(10) NOT NULL,
    CLOCK_IN TIME,
    CLOCK_OUT TIME,
    WORKING_HOURS DECIMAL(5, 2) NOT NULL,
    OVERTIME_HOURS DECIMAL(5, 2) NOT NULL,
    NIGHT_HOURS DECIMAL(5, 2) NOT NULL,
    IS_FINALIZED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (EMP_ID) REFERENCES emp(EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


-- 休憩
CREATE TABLE break (
    BREAK_ID INT PRIMARY KEY AUTO_INCREMENT,
    KINTAI_REC_ID INT NOT NULL,
    EMP_ID VARCHAR(10) NOT NULL,
    BREAK_START TIME,
    BREAK_END TIME,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL,
    FOREIGN KEY (KINTAI_REC_ID) REFERENCES kintai(KINTAI_REC_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EMP_ID) REFERENCES emp(EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 休暇記録
CREATE TABLE leave_rec (
    LEAVE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_ID VARCHAR(10) NOT NULL,
    LEAVE_TYPE_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    REASON VARCHAR(200),
    APPROVED_BY VARCHAR(50),
    STATUS VARCHAR(20),
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES emp(EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES leave_type(LEAVE_TYPE_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 休暇残日数管理
CREATE TABLE leave_balance (
    BALANCE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_ID VARCHAR(10) NOT NULL,
    LEAVE_TYPE_ID INT NOT NULL,
    GRANT_DATE DATE NOT NULL,
    EXPIRE_DATE DATE NOT NULL,
    GRANTED_DAYS INT NOT NULL,
    USED_DAYS INT NOT NULL DEFAULT 0,
    SOURCE VARCHAR(20) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL,
    UNIQUE (EMP_ID, LEAVE_TYPE_ID, GRANT_DATE),
    FOREIGN KEY (EMP_ID) REFERENCES emp(EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES leave_type(LEAVE_TYPE_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 工数割当
CREATE TABLE work_alloc (
    ALLOCATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_ID VARCHAR(10) NOT NULL,
    PROJECT_ID INT NOT NULL,
    WORK_DATE DATE NOT NULL,
    WORK_HOURS DECIMAL(5, 2) NOT NULL,
    IS_FINALIZED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL,
    UNIQUE (EMP_ID, PROJECT_ID, WORK_DATE),
    FOREIGN KEY (EMP_ID) REFERENCES emp(EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (PROJECT_ID) REFERENCES project(PROJECT_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 月次時給
CREATE TABLE hourly_rate_monthly (
    RATE_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_ID VARCHAR(10) NOT NULL,
    PROJECT_ID INT NOT NULL,
    TARGET_MONTH DATE NOT NULL,
    HOURLY_RATE DECIMAL(7,2) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    DELETED_AT DATETIME DEFAULT NULL,
    DELETED_BY VARCHAR(10),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(10) NOT NULL,
    UNIQUE (EMP_ID, PROJECT_ID, TARGET_MONTH),
    FOREIGN KEY (EMP_ID) REFERENCES emp(EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (PROJECT_ID) REFERENCES project(PROJECT_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


--テストデータ
INSERT INTO role (ROLE_ID, ROLE_NAME) VALUES
(0, '一般ユーザー'),
(1, '管理者'),
(2, '部長');

INSERT INTO dept (DEPT_ID, DEPT_NAME, IS_DELETED, DELETED_AT, DELETED_BY, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES
('D01', '管理部', FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
('D02', '営業部', FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin');

INSERT INTO post (POST_ID, POST_NAME, IS_DELETED, DELETED_AT, DELETsleED_BY, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES
('P01', '一般社員', FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
('P02', '主任', FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
('P03', '部長', FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin');

INSERT INTO leave_type (LEAVE_TYPE_ID, LEAVE_TYPE_NAME, IS_PAID, IS_SYSTEM_DEFINED, IS_DELETED, DELETED_AT, DELETED_BY, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES
(1, '年次有給休暇', TRUE, TRUE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(2, '特別休暇', TRUE, TRUE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(3, '代休', TRUE, TRUE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(11, '初回付与（3か月）', TRUE, TRUE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(12, '初回付与（6か月）', TRUE, TRUE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(20, '産休', FALSE, FALSE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(30, '慶弔休暇', TRUE, FALSE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(40, 'その他(有給)', TRUE, FALSE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin'),
(41, 'その他(無給)', FALSE, FALSE, FALSE, NULL, NULL, NOW(), 'admin', NOW(), 'admin');


INSERT INTO emp (EMP_ID, EMP_NAME, DEPT_ID, POST_ID, ROLE_ID, EMP_TYPE, PASS, MAIL, EMP_DATE, IS_ACTIVE, LEAVE_DATE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES
('E001', '田中 太郎', 'D01', 'P01', 1, '正社員', 'pass1', 'tanaka@example.com', '2022-04-01', TRUE, NULL, NOW(), 'admin', NOW(), 'admin'),
('E002', '佐藤 花子', 'D02', 'P02', 2, '正社員', 'pass2', 'sato@example.com', '2023-01-15', TRUE, NULL, NOW(), 'admin', NOW(), 'admin'),
('E003', '鈴木 一郎', 'D02', 'P03', 0, '正社員', 'pass3', 'suzuki@example.com', '2020-07-01', TRUE, NULL, NOW(), 'admin', NOW(), 'admin');

-- プロジェクトテストデータ
INSERT INTO project (PROJECT_NAME, BUDGET_AMOUNT, ACTUAL_COST, ACTUAL_LABOR_COST, START_DATE, END_DATE, IS_ACTIVE, IS_DELETED, DELETED_AT, DELETED_BY, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES
('ECサイト構築プロジェクト', 5000000, 3200000, 2800000, '2025-01-01', '2025-06-30', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('顧客管理システム改修', 3000000, 2100000, 1900000, '2025-02-01', '2025-05-31', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('社内勤怠システム開発', 2500000, 1800000, 1600000, '2024-10-01', '2025-03-31', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('データベース移行', 1500000, 900000, 800000, '2025-03-01', '2025-04-30', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('モバイルアプリ開発', 4000000, 2500000, 2200000, '2025-01-15', '2025-08-31', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('AI画像認識システム', 6000000, 0, 0, '2025-04-01', '2025-12-31', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('セキュリティ強化', 1800000, 1200000, 1000000, '2024-12-01', '2025-02-28', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('業務効率化ツール', 2200000, 1500000, 1300000, '2024-11-01', '2025-04-30', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('クラウド移行', 3500000, 2800000, 2400000, '2024-09-01', '2025-02-28', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('レポート自動化', 1200000, 800000, 700000, '2025-02-15', '2025-05-15', TRUE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001');

-- 工数割当テストデータ
INSERT INTO work_alloc (EMP_ID, PROJECT_ID, WORK_DATE, WORK_HOURS, IS_FINALIZED, IS_DELETED, DELETED_AT, DELETED_BY, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES
('E001', 1, '2025-01-15', 8.00, FALSE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('E001', 2, '2025-02-10', 6.50, FALSE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('E002', 1, '2025-01-16', 7.50, FALSE, FALSE, NULL, NULL, NOW(), 'E002', NOW(), 'E002'),
('E002', 3, '2025-01-20', 8.00, FALSE, FALSE, NULL, NULL, NOW(), 'E002', NOW(), 'E002'),
('E003', 4, '2025-03-05', 5.00, FALSE, FALSE, NULL, NULL, NOW(), 'E003', NOW(), 'E003'),
('E001', 5, '2025-01-25', 7.00, FALSE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('E002', 6, '2025-04-10', 8.00, FALSE, FALSE, NULL, NULL, NOW(), 'E002', NOW(), 'E002'),
('E003', 7, '2025-01-08', 6.00, FALSE, FALSE, NULL, NULL, NOW(), 'E003', NOW(), 'E003'),
('E001', 8, '2025-02-20', 7.50, FALSE, FALSE, NULL, NULL, NOW(), 'E001', NOW(), 'E001'),
('E002', 9, '2025-01-30', 8.00, FALSE, FALSE, NULL, NULL, NOW(), 'E002', NOW(), 'E002');